server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://<LOKI_HOST>:3100/loki/api/v1/push

positions:
  filename: /var/log/positions.yaml

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
